2023.04.10 장바구니 기능 구현 - 장바구니 테이블 생성, 상품을 장바구니에 추가, 상품 번호가 장바구니에 담겨져있는지 조회(상품 추가 전인지, 이미 추가된 상품인지 체크), 장바구니 목록 조회, 상품정보 세션에 바인딩
1. 장바구니 관련 기능 작성 후 메인페이지 들어갈 때 발생한 오류
org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException:
Error creating bean with name 'sqlSessionFactory' defined in ServletContext resource [/WEB-INF/spring/action-mybatis.xml]:
Invocation of init method failed;
nested exception is org.springframework.core.NestedIOException:
Failed to parse mapping resource:
'file [C:\Users\hi\Documents\workspace-sts-3.9.10.RELEASE\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\bookarchive\WEB-INF\classes\mybatis\mappers\cart.xml]';
nested exception is java.lang.RuntimeException:
Error parsing Mapper XML.
Cause: org.apache.ibatis.builder.BuilderException: Error resolving class .
Cause: org.apache.ibatis.type.TypeException:
Could not resolve type alias 'CartVO'.
Cause: java.lang.ClassNotFoundException: Cannot find class: CartVO
해결 : modelConfig 파일에 CartVO type alias 추가해서 해결 !

2. ctrl+shift+R : 파일 찾을 때 사용

3.  장바구니 구현 기능 중 : 장바구니 페이지에서 수량 변경하면 가격은 반영되는데 수량이 반영안되는 문제 발생함
<해결> 화면단의 문제이기 때문에 jsp 수정해서 해결, 수량과 장바구니에 담은 책의 속성 따로 분리하여 생각하여야 함.

**세션 종료할 때 warning
4월 10, 2023 12:17:46 오후 org.apache.catalina.session.StandardSession doWriteObject
WARNING: 세션 [8E302E7E1BB8D95BA845725B3FE3699F]을(를) 위한 세션 속성 [quickGoodsList]을(를) 직렬화할 수 없습니다.
java.io.NotSerializableException: com.myspring.bookarchive.goods.vo.GoodsVO

4월 10, 2023 12:17:46 오후 org.apache.catalina.session.StandardSession doWriteObject
WARNING: 세션 [8E302E7E1BB8D95BA845725B3FE3699F]을(를) 위한 세션 속성 [cartMap]을(를) 직렬화할 수 없습니다.
java.io.NotSerializableException: com.myspring.bookarchive.cart.vo.CartVO

----------------------------------------------------------------------------------------------------------------------------
**해결 중** (회원가입 폼)
2. 회원가입 이후에 sqldeveloper에 한글 깨져서 뜸
3. 회원가입 후에 메인 화면으로 안 돌아가고 빈 화면이 뜸
(localhost:8080/bookarchive/member/addMember.do)

2. 한글 이미지 파일 명 불러올 때 깨져서 화면에 안 나오는 현상
톰캣 서버 server.xml 에서 서버 설정 파일에서 URIencoding 속성 추가 (euc-kr)
// 이미지 파일명 인코딩은 해결완료, sql developer에서 나타나는 한글 깨짐 현상 해결 필요

<시도해본 해결방법>
1. window - preferences 내에 있는 workspace, xmlFile, JspFile  내의 인코딩 변경 ==> 실패
2. server.xml 의 Uriencoding ==> 실패
3. SQL 설정 변경
(3-1) SELECT
 (SELECT VALUE FROM NLS_DATABASE_PARAMETERS WHERE PARAMETER='NLS_LANGUAGE')
    || '_' ||
    (SELECT VALUE FROM NLS_DATABASE_PARAMETERS WHERE PARAMETER='NLS_TERRITORY')
    || '.' ||
    (SELECT VALUE FROM NLS_DATABASE_PARAMETERS WHERE PARAMETER='NLS_CHARACTERSET')
FROM DUAL;
(3-2) select * from nls_database_parameters where parameter = 'NLS_CHARACTERSET';
(3-3) SELECT * FROM sys.props$ where name like '%CHARACTERSET%';
==> 속성 확인해봤으나 실패
4. controller ->  "/addMember" 인코딩 확인 ==>문제없음
5. sql에서 직접 입력해서 insert 할 경우 한글 깨지지않고 들어감

3.  /addMember.do 까지 매핑됐는데 이후에 redirect에 문제가 있음