2023.04.12 에러해결(2) : '/addMember.do' 이후에 redirect mapping 문제 해결 <해결 완료> 1. 회원가입 후에 메인 화면으로 안 돌아가고 빈 화면이 뜸 (localhost:8080/bookarchive/member/addMember.do)
<해결 완료>
memberDAO : insertNewMember
MemberDAOImpl : insertNewMember
MemberServiceImpl : insertNewMember
관련 부분 확인 중 ===> /addMember.do 까지 매핑됐는데 이후에 redirect에 문제가 있음
<해결> servlet-context, action-mybatis 내용 확인
xmlns:tx, xmlns:context 삭제 => xmlns:aop 로 변경
 <bean id="transactionManager"
  class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
  <property name="dataSource" ref="dataSource"></property>
 </bean>
추가해서 해결

2. 홈페이지 내부 인코딩 이슈 ... (회원가입, 마이페이지, 주문 기능 등)
: 따로 오류가 발생하지 않고 인코딩만 되지 않는 오류 발생

<해결>
(1) STS 인코딩 설정
(1-1) general-workspace -text File encoding => utf-8
(1-2) general-editors -text editors - spelling - encoding => utf-8
(1-3) web - css Files => utf-8
web - HTML files => utf-8
web - jsp files encoding => utf-8
==========> 실패.. 이클립스 sts console창이 깨짐 (workspace text file encoding => default로 되돌려서 해결)

(2) web. xml 에서 <filter> 내의 내용 수정
 <filter>
  <filter-name>encodingFilter</filter-name>
  <filter-class>
   org.springframework.web.filter.CharacterEncodingFilter
  </filter-class>
  <init-param>
   <param-name>encoding</param-name>
   <param-name>UTF-8</param-name>
  </init-param>
  <init-param>
   <param-name>forceEncoding</param-name>
   <param-value>true</param-value>
  </init-param>
 </filter>

 <filter-mapping>
  <filter-name>encodingFilter</filter-name>
  <url-pattern>/*</url-pattern>
 </filter-mapping>
: "forceEncoding" 추가 => 해결 X

(3) SQL developer에서 도구-환경설정-환경-인코딩 utf-8로 변경 => 해결 X

(4)Servers - server.xml => connector 찾아서 URIEncoding="UTF-8" 추가 => 해결 X
<Connector connectionTimeout="20000" port="8080" protocol="HTTP/1.1" redirectPort="8443" URIEncoding="UTF-8"/>
<Connector port="8009" protocol="AJP/1.3" redirectPort="8443"URIEncoding="UTF-8"/>

(5) SQL develpper 데이터베이스 문자셋 확인..
select value FROM nls_database_parameters WHERE parameter='NLS_CHARACTERSET';
=> K016MSWIN949 문제 없음.. 해결 X

(6)  클라이언트 문자셋 설정 확인 및 변경
SQL PLUS => SHOW NLS_LANG;
: (6-1) 알 수 없는 show 옵션으로 뜸
: (6-2) SELECT USERENV('LANG') FROM DUAL;
=> KO로 뜸,,, 문제 없음 해결 X

(7) 윈도우 레지스트리 편집기
: 컴퓨터 - HKEY_LOCAL_MACHINE - SOFTWARE - ORACLE - KEY_OraDb11g_home1 - NLS_LANG
=> 데이터 확인 => KOREAN_KOREA.KO16MSWIN949 ... 확인 문제 없음 해결 X

(8).. 문제가 발생한 member쪽 기능을 모두 갈아엎어보기로 함..  => addMember.do 문제 해결, 인코딩 문제는 미해결
member.xml
memberVO
memberDAO, memberDAOImpl
memberService, memberServiceImpl
modelConfig
tiles_member
((board와 관련된 내용 모두 삭제))

(8-1)
SEVERE: Context initialized 이벤트를 [org.springframework.web.context.ContextLoaderListener] 클래스의 인스턴스인 리스너에 전송하는 동안 예외 발생
org.springframework.beans.factory.BeanCreationException:
Error creating bean with name 'sqlSessionFactory' defined in ServletContext resource [/WEB-INF/spring/action-mybatis.xml]:
 Invocation of init method failed; nested exception is java.io.FileNotFoundException:
class path resource [mybatis/models/modelConfig.xml] cannot be opened because it does not exist
<해결>action-mybais.xml 내의
<sqlSessionFactory>의 configLocation property의 value (classpath) 수정하여 해결

(8-2)
ERROR: org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException:
Error creating bean with name 'sqlSessionFactory' defined in ServletContext resource
[/WEB-INF/spring/action-mybatis.xml]:
Invocation of init method failed; nested exception is org.springframework.core.NestedIOException:
Failed to parse mapping resource: 'file [C:\Users\hi\Documents\workspace-sts-3.9.10.RELEASE\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\bookarchive\WEB-INF\classes\mybatis\mappers\board.xml]';
nested exception is java.lang.RuntimeException: Error parsing Mapper XML. Cause: org.apache.ibatis.builder.BuilderException:
Error resolving class . Cause: org.apache.ibatis.type.TypeException: Could not resolve type alias 'articleVO'.  Cause: java.lang.ClassNotFoundException: Cannot find class: articleVO
((board와 관련된 내용 모두 삭제)) => xml파일 중에 board.xml 제대로 삭제 안 해서 오류 발생 => 해결